version: '3.8'

services:

  db:
    container_name: postgres-rdkit
    image: mcs07/postgres-rdkit
    restart: always
    environment:
      POSTGRES_PASSWORD: key3rxns
      POSTGRES_DB: cgemdb
    volumes:
      - /path/to/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_net: 
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "5050:80"
    networks:
      app_net: 
        ipv4_address: 192.168.0.3

networks:
  app_net: 
    ipam: 
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1